/**
 * JDialogPaciente.java
 * 22/11/2015
 */
package org.dental.pantallas;

import java.awt.Dimension;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.dental.constantes.ConstantesTipoLetra;
import org.dental.constantes.ConstantesURLS;

/**
 *
 * @author Henry Salinas A.
 * @version: 1.0
 */
public class JDialogPaciente extends javax.swing.JDialog {

    private static final Integer ANCHO_PANTALLA = 890;
    private static final Integer ALTO_PANTALLA = 605;
    private final static Dimension SCREEN_SIZE = new Dimension(ANCHO_PANTALLA, ALTO_PANTALLA);

    private static byte[] ARREGLO_BYTES_FOTO = null;
    private static String PATH_IMAGEN = "";

    /**
     * Creates new form JDialogPaciente
     *
     * @param parent
     * @param modal
     */
    public JDialogPaciente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.pack();
        ImageIcon iconoVentana = new ImageIcon(getClass().getResource(ConstantesURLS.RUTA_IMAGEN_FONDO_SECUNDARIO));
        Image imagen = iconoVentana.getImage().getScaledInstance((SCREEN_SIZE.width), (SCREEN_SIZE.height), Image.SCALE_AREA_AVERAGING);
        jLblFondo.setIcon(new ImageIcon(imagen));
        jLblFondo.setSize(SCREEN_SIZE);
        this.setSize(SCREEN_SIZE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPacientes = new javax.swing.JLayeredPane();
        jLlbIdentificacion = new javax.swing.JLabel();
        jLblLeyendaInformacionPersonal = new javax.swing.JLabel();
        jLblLeyendaInformacionContacto = new javax.swing.JLabel();
        jLlbNombres = new javax.swing.JLabel();
        jLlbApellidos = new javax.swing.JLabel();
        jTxtIdentificacion = new javax.swing.JTextField();
        jTxtApellidos = new javax.swing.JTextField();
        jTxtNombres = new javax.swing.JTextField();
        jLblTelefono = new javax.swing.JLabel();
        jLblMail = new javax.swing.JLabel();
        jTxtCelular = new javax.swing.JTextField();
        jTxtTelefono = new javax.swing.JTextField();
        jLlbHistoriaClinica = new javax.swing.JLabel();
        jTxtNumHistoriaClinica = new javax.swing.JTextField();
        jLlbFechaNacimiento = new javax.swing.JLabel();
        jDateFechaNacimiento = new com.toedter.calendar.JDateChooser();
        jlblImagen = new javax.swing.JLabel();
        jBntImagen = new javax.swing.JButton();
        jlblImagenCargada = new javax.swing.JLabel();
        jBntQuitarFoto = new javax.swing.JButton();
        jScrollPanelAlertas = new javax.swing.JScrollPane();
        jTblProductos = new javax.swing.JTable();
        jLlbGenero = new javax.swing.JLabel();
        jComboGenero = new javax.swing.JComboBox<>();
        jLblCelular1 = new javax.swing.JLabel();
        jTxtCelular1 = new javax.swing.JTextField();
        jBntagregarAlertas = new javax.swing.JButton();
        jlblImagen1 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuevo paciente");
        setResizable(false);
        getContentPane().setLayout(null);

        jLayeredPacientes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingreso Pacientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Copperplate Gothic Light", 0, 14), new java.awt.Color(0, 102, 153))); // NOI18N
        jLayeredPacientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLlbIdentificacion.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLlbIdentificacion.setText("Identificación:");
        jLayeredPacientes.add(jLlbIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 67, -1, -1));

        jLblLeyendaInformacionPersonal.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLblLeyendaInformacionPersonal.setForeground(new java.awt.Color(0, 102, 153));
        jLblLeyendaInformacionPersonal.setText("Información Personal");
        jLayeredPacientes.add(jLblLeyendaInformacionPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 30, -1, -1));

        jLblLeyendaInformacionContacto.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLblLeyendaInformacionContacto.setForeground(new java.awt.Color(0, 102, 153));
        jLblLeyendaInformacionContacto.setText("Información Contacto");
        jLayeredPacientes.add(jLblLeyendaInformacionContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 265, -1, -1));

        jLlbNombres.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLlbNombres.setText("Nombres:");
        jLayeredPacientes.add(jLlbNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 127, -1, -1));

        jLlbApellidos.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLlbApellidos.setText("Apellidos:");
        jLayeredPacientes.add(jLlbApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 157, -1, -1));

        jTxtIdentificacion.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLayeredPacientes.add(jTxtIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 62, 234, -1));

        jTxtApellidos.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLayeredPacientes.add(jTxtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 149, 234, -1));

        jTxtNombres.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLayeredPacientes.add(jTxtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 121, 234, -1));

        jLblTelefono.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLblTelefono.setText("Teléfono:");
        jLayeredPacientes.add(jLblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 290, -1, -1));

        jLblMail.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLblMail.setText("Mail:");
        jLayeredPacientes.add(jLblMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 346, -1, -1));

        jTxtCelular.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLayeredPacientes.add(jTxtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 340, 230, -1));

        jTxtTelefono.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLayeredPacientes.add(jTxtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 285, 230, -1));

        jLlbHistoriaClinica.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLlbHistoriaClinica.setText("N° Historia Clínica:");
        jLayeredPacientes.add(jLlbHistoriaClinica, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 97, 132, -1));

        jTxtNumHistoriaClinica.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLayeredPacientes.add(jTxtNumHistoriaClinica, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 92, 234, -1));

        jLlbFechaNacimiento.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLlbFechaNacimiento.setText("Fecha Nacimiento:");
        jLayeredPacientes.add(jLlbFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 187, -1, -1));

        jDateFechaNacimiento.setMaxSelectableDate(new Date());
        jLayeredPacientes.add(jDateFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 177, 232, -1));

        jlblImagen.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jlblImagen.setForeground(new java.awt.Color(0, 102, 153));
        jlblImagen.setText("Imagen");
        jLayeredPacientes.add(jlblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 30, -1, -1));

        jBntImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dental/imagenes/SeleccionarFoto_24x24.png"))); // NOI18N
        jBntImagen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBntImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBntImagenActionPerformed(evt);
            }
        });
        jLayeredPacientes.add(jBntImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 63, 30, 30));

        jlblImagenCargada.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 102, 153)));
        jlblImagenCargada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLayeredPacientes.add(jlblImagenCargada, new org.netbeans.lib.awtextra.AbsoluteConstraints(573, 62, 180, 180));

        jBntQuitarFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dental/imagenes/Suprimir_24x24.png"))); // NOI18N
        jBntQuitarFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBntQuitarFoto.setEnabled(false);
        jBntQuitarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBntQuitarFotoActionPerformed(evt);
            }
        });
        jLayeredPacientes.add(jBntQuitarFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 110, 30, 30));

        jTblProductos.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTblProductos.setEnabled(false);
        jTblProductos.setRowHeight(25);
        jScrollPanelAlertas.setViewportView(jTblProductos);

        jLayeredPacientes.add(jScrollPanelAlertas, new org.netbeans.lib.awtextra.AbsoluteConstraints(573, 285, 180, 130));

        jLlbGenero.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLlbGenero.setText("Género:");
        jLayeredPacientes.add(jLlbGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 217, -1, -1));

        jComboGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        jLayeredPacientes.add(jComboGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 232, -1));

        jLblCelular1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLblCelular1.setText("Celular:");
        jLayeredPacientes.add(jLblCelular1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 318, -1, -1));

        jTxtCelular1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLayeredPacientes.add(jTxtCelular1, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 313, 230, -1));

        jBntagregarAlertas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dental/imagenes/Agregar_24x24.png"))); // NOI18N
        jBntagregarAlertas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLayeredPacientes.add(jBntagregarAlertas, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 285, 30, 30));

        jlblImagen1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jlblImagen1.setForeground(new java.awt.Color(0, 102, 153));
        jlblImagen1.setText("Alertas Médicas");
        jLayeredPacientes.add(jlblImagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 265, -1, -1));

        getContentPane().add(jLayeredPacientes);
        jLayeredPacientes.setBounds(30, 30, 790, 450);

        btnGuardar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnGuardar.setText("Guardar");
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(330, 500, 81, 25);

        btnCancelar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnCancelar.setText("Cancelar");
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(420, 500, 87, 25);

        jLblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dental/imagenes/FondoSecundario.jpg"))); // NOI18N
        getContentPane().add(jLblFondo);
        jLblFondo.setBounds(0, 0, 890, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBntImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBntImagenActionPerformed
        JFileChooser dialogo = new JFileChooser();
        dialogo.setFileFilter(new FileNameExtensionFilter("Imagenes JPG", "jpg"));
        dialogo.setDialogTitle("Seleccione la imagen del producto");
        int opcionSeleccion = dialogo.showOpenDialog(this);
        if (opcionSeleccion == JFileChooser.APPROVE_OPTION) {
            jlblImagenCargada.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font(ConstantesTipoLetra.COPPERPLATE_TYPE, ConstantesTipoLetra.COPPERPLATE_STYLE, 13), new java.awt.Color(0, 0, 255)));
            //LOG.info("Imagen seleccionada: " + dialogo.getSelectedFile().toString());
            PATH_IMAGEN = dialogo.getSelectedFile().toString();
            URL url = null;
            try {
                url = dialogo.getSelectedFile().toURL();
            } catch (MalformedURLException ex) {
                //LOG.error("Error al escoger la imagen. ", ex);
            }
            ImageIcon icon = new ImageIcon(url);
            Image imagen = icon.getImage().getScaledInstance((jlblImagenCargada.getWidth() - 20), (jlblImagenCargada.getHeight() - 20), Image.SCALE_AREA_AVERAGING);
            jlblImagenCargada.setIcon(new ImageIcon(imagen));
            ARREGLO_BYTES_FOTO = convertirImagenArregloBytes();
            jBntQuitarFoto.setEnabled(true);
        }
    }//GEN-LAST:event_jBntImagenActionPerformed

    private void jBntQuitarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBntQuitarFotoActionPerformed
        ARREGLO_BYTES_FOTO = null;
        PATH_IMAGEN = "";
        jlblImagenCargada.setIcon(null);
        jBntQuitarFoto.setEnabled(false);
    }//GEN-LAST:event_jBntQuitarFotoActionPerformed

    private byte[] convertirImagenArregloBytes() {
        byte[] bufferImagen = null;
        if (!"".equals(PATH_IMAGEN)) {
            bufferImagen = new byte[1024];
            try {
                FileInputStream fileInputStream = new FileInputStream(PATH_IMAGEN);
                ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
                for (int readNum; (readNum = fileInputStream.read(bufferImagen)) != -1;) {
                    byteArrayOutputStream.write(bufferImagen, 0, readNum);
                }
                bufferImagen = byteArrayOutputStream.toByteArray();
            } catch (FileNotFoundException fileException) {
                //LOG.error("No encontro la imagen", fileException);
            } catch (IOException io) {
                //LOG.error("Error de escritura de la imagen", io);
            }
        }
        return bufferImagen;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogPaciente dialog = new JDialogPaciente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton jBntImagen;
    private javax.swing.JButton jBntQuitarFoto;
    private javax.swing.JButton jBntagregarAlertas;
    private javax.swing.JComboBox<String> jComboGenero;
    private com.toedter.calendar.JDateChooser jDateFechaNacimiento;
    private javax.swing.JLayeredPane jLayeredPacientes;
    private javax.swing.JLabel jLblCelular1;
    private javax.swing.JLabel jLblFondo;
    private javax.swing.JLabel jLblLeyendaInformacionContacto;
    private javax.swing.JLabel jLblLeyendaInformacionPersonal;
    private javax.swing.JLabel jLblMail;
    private javax.swing.JLabel jLblTelefono;
    private javax.swing.JLabel jLlbApellidos;
    private javax.swing.JLabel jLlbFechaNacimiento;
    private javax.swing.JLabel jLlbGenero;
    private javax.swing.JLabel jLlbHistoriaClinica;
    private javax.swing.JLabel jLlbIdentificacion;
    private javax.swing.JLabel jLlbNombres;
    private javax.swing.JScrollPane jScrollPanelAlertas;
    private javax.swing.JTable jTblProductos;
    private javax.swing.JTextField jTxtApellidos;
    private javax.swing.JTextField jTxtCelular;
    private javax.swing.JTextField jTxtCelular1;
    private javax.swing.JTextField jTxtIdentificacion;
    private javax.swing.JTextField jTxtNombres;
    private javax.swing.JTextField jTxtNumHistoriaClinica;
    private javax.swing.JTextField jTxtTelefono;
    private javax.swing.JLabel jlblImagen;
    private javax.swing.JLabel jlblImagen1;
    private javax.swing.JLabel jlblImagenCargada;
    // End of variables declaration//GEN-END:variables
}
