/**
 * JDialogExamen.java
 * 15/12/2015
 */
package org.dental.pantallas;

import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;
import org.dental.constantes.ConstantesURLDientes;
import org.dental.constantes.ConstantesURLS;

/**
 *
 * @author Henry Salinas A.
 * @version: 1.0
 */
public class JDialogPeriodontograma extends javax.swing.JDialog {

    private static final Integer ANCHO_PANTALLA = 1300;
    private static final Integer ALTO_PANTALLA = 670;
    private final static Dimension SCREEN_SIZE = new Dimension(ANCHO_PANTALLA, ALTO_PANTALLA);

    /**
     * Creates new form JDialogExamen
     *
     * @param parent
     * @param modal
     */
    public JDialogPeriodontograma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ImageIcon iconoVentana = new ImageIcon(getClass().getResource(ConstantesURLS.RUTA_IMAGEN_FONDO_SECUNDARIO));
        Image imagen = iconoVentana.getImage().getScaledInstance((SCREEN_SIZE.width), (SCREEN_SIZE.height), Image.SCALE_AREA_AVERAGING);
        jLblFondo.setIcon(new ImageIcon(imagen));
        jLblFondo.setSize(SCREEN_SIZE);
        this.setSize(SCREEN_SIZE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSuperiorVestibularCuadranteUno = new javax.swing.JPanel();
        jLlbIProfundidadSondaje = new javax.swing.JLabel();
        jLlbTitulo11 = new javax.swing.JLabel();
        jLlbIMovilidad = new javax.swing.JLabel();
        jLlbIPronostico = new javax.swing.JLabel();
        jLlbISangradoSuturacion = new javax.swing.JLabel();
        jLlbIPlaca = new javax.swing.JLabel();
        jLlbIAnchuraEncia = new javax.swing.JLabel();
        jLlbIMargenGingival = new javax.swing.JLabel();
        jLlbIFurca = new javax.swing.JLabel();
        jLlbIImplante1 = new javax.swing.JLabel();
        jLlbTitulo18 = new javax.swing.JLabel();
        jLlbTitulo17 = new javax.swing.JLabel();
        jLlbTitulo16 = new javax.swing.JLabel();
        jLlbTitulo15 = new javax.swing.JLabel();
        jLlbTitulo14 = new javax.swing.JLabel();
        jLlbTitulo13 = new javax.swing.JLabel();
        jLlbTitulo12 = new javax.swing.JLabel();
        jSpdTop = new javax.swing.JSeparator();
        jSpt1 = new javax.swing.JSeparator();
        jBtnImplante18 = new javax.swing.JButton();
        jSpt3 = new javax.swing.JSeparator();
        jSpt2 = new javax.swing.JSeparator();
        jLblFurcaSobreImagen18 = new javax.swing.JLabel();
        jLblImagenVestibularDiente18 = new javax.swing.JLabel();
        jTxtMargenGingivalMedia18 = new javax.swing.JLabel();
        jTxtAnchuraEncia18 = new javax.swing.JLabel();
        jTxtMargenGingivalMesial18 = new javax.swing.JLabel();
        jTxtMargenGingivalDistal18 = new javax.swing.JLabel();
        jTxtProfundidadMesial18 = new javax.swing.JLabel();
        jTxtProfundidadMedia18 = new javax.swing.JLabel();
        jTxtProfundidadDistal18 = new javax.swing.JLabel();
        jTxtPlacaMesial18 = new javax.swing.JLabel();
        jTxtPlacaMedia18 = new javax.swing.JLabel();
        jTxtPlacaDistal18 = new javax.swing.JLabel();
        jTxtSangradoMesial18 = new javax.swing.JLabel();
        jTxtSangradoMedia18 = new javax.swing.JLabel();
        jTxtSangradoDistal18 = new javax.swing.JLabel();
        jTxtFurca18 = new javax.swing.JLabel();
        jTxtMovilidad18 = new javax.swing.JLabel();
        jTxtPronosticoIndividual18 = new javax.swing.JLabel();
        jBtnImplante17 = new javax.swing.JButton();
        jTxtMovilidad17 = new javax.swing.JLabel();
        jTxtPronosticoIndividual17 = new javax.swing.JLabel();
        jTxtFurca17 = new javax.swing.JLabel();
        jTxtSangradoMesial17 = new javax.swing.JLabel();
        jTxtPlacaMesial17 = new javax.swing.JLabel();
        jTxtAnchuraEncia17 = new javax.swing.JLabel();
        jTxtMargenGingivalMesial17 = new javax.swing.JLabel();
        jTxtProfundidadMesial17 = new javax.swing.JLabel();
        jLblFurcaSobreImagen17 = new javax.swing.JLabel();
        jLblImagenVestibularDiente17 = new javax.swing.JLabel();
        jTxtPlacaMedia17 = new javax.swing.JLabel();
        jTxtSangradoMedia17 = new javax.swing.JLabel();
        jTxtSangradoDistal17 = new javax.swing.JLabel();
        jTxtPlacaDistal17 = new javax.swing.JLabel();
        jTxtMargenGingivalMedia17 = new javax.swing.JLabel();
        jTxtProfundidadMedia17 = new javax.swing.JLabel();
        jTxtMargenGingivalDistal17 = new javax.swing.JLabel();
        jTxtProfundidadDistal17 = new javax.swing.JLabel();
        jSpt4 = new javax.swing.JSeparator();
        jSpt5 = new javax.swing.JSeparator();
        jSpt6 = new javax.swing.JSeparator();
        jSpt7 = new javax.swing.JSeparator();
        jSpt8 = new javax.swing.JSeparator();
        jSpt9 = new javax.swing.JSeparator();
        jBtnImplante11 = new javax.swing.JButton();
        jTxtMovilidad11 = new javax.swing.JLabel();
        jTxtPronosticoIndividual11 = new javax.swing.JLabel();
        jTxtFurca11 = new javax.swing.JLabel();
        jTxtSangradoMesial11 = new javax.swing.JLabel();
        jTxtPlacaMesial11 = new javax.swing.JLabel();
        jTxtAnchuraEncia11 = new javax.swing.JLabel();
        jTxtMargenGingivalMesial11 = new javax.swing.JLabel();
        jTxtProfundidadMesial11 = new javax.swing.JLabel();
        jLblImagenVestibularDiente11 = new javax.swing.JLabel();
        jLblImagenVestibularDiente12 = new javax.swing.JLabel();
        jLblImagenVestibularDiente13 = new javax.swing.JLabel();
        jLblImagenVestibularDiente14 = new javax.swing.JLabel();
        jLblImagenVestibularDiente15 = new javax.swing.JLabel();
        jLblImagenVestibularDiente16 = new javax.swing.JLabel();
        jLblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Periodontograma");
        getContentPane().setLayout(null);

        jPanelSuperiorVestibularCuadranteUno.setBackground(java.awt.Color.white);
        jPanelSuperiorVestibularCuadranteUno.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Copperplate Gothic Light", 0, 14), new java.awt.Color(0, 153, 153))); // NOI18N
        jPanelSuperiorVestibularCuadranteUno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLlbIProfundidadSondaje.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLlbIProfundidadSondaje.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLlbIProfundidadSondaje.setText("Profundidad de sondaje");
        jPanelSuperiorVestibularCuadranteUno.add(jLlbIProfundidadSondaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 160, 20));

        jLlbTitulo11.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLlbTitulo11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLlbTitulo11.setText("1.1");
        jLlbTitulo11.setToolTipText("");
        jLlbTitulo11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jLlbTitulo11, new org.netbeans.lib.awtextra.AbsoluteConstraints(767, 10, 40, -1));

        jLlbIMovilidad.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLlbIMovilidad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLlbIMovilidad.setText("Movilidad");
        jPanelSuperiorVestibularCuadranteUno.add(jLlbIMovilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 160, 20));

        jLlbIPronostico.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLlbIPronostico.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLlbIPronostico.setText("Pronóstico individual");
        jPanelSuperiorVestibularCuadranteUno.add(jLlbIPronostico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 160, 20));

        jLlbISangradoSuturacion.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLlbISangradoSuturacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLlbISangradoSuturacion.setText("Sangrado / Supuración");
        jPanelSuperiorVestibularCuadranteUno.add(jLlbISangradoSuturacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 160, 20));

        jLlbIPlaca.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLlbIPlaca.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLlbIPlaca.setText("Placa");
        jPanelSuperiorVestibularCuadranteUno.add(jLlbIPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 160, 20));

        jLlbIAnchuraEncia.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLlbIAnchuraEncia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLlbIAnchuraEncia.setText("Anchura encía");
        jPanelSuperiorVestibularCuadranteUno.add(jLlbIAnchuraEncia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 160, 20));

        jLlbIMargenGingival.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLlbIMargenGingival.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLlbIMargenGingival.setText("Margen gingival");
        jPanelSuperiorVestibularCuadranteUno.add(jLlbIMargenGingival, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 160, 20));

        jLlbIFurca.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLlbIFurca.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLlbIFurca.setText("Furca");
        jPanelSuperiorVestibularCuadranteUno.add(jLlbIFurca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 160, 20));

        jLlbIImplante1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLlbIImplante1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLlbIImplante1.setText("Implante");
        jPanelSuperiorVestibularCuadranteUno.add(jLlbIImplante1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 160, 20));

        jLlbTitulo18.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLlbTitulo18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLlbTitulo18.setText("1.8");
        jLlbTitulo18.setToolTipText("");
        jLlbTitulo18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jLlbTitulo18, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 40, -1));

        jLlbTitulo17.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLlbTitulo17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLlbTitulo17.setText("1.7");
        jLlbTitulo17.setToolTipText("");
        jLlbTitulo17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jLlbTitulo17, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 10, 40, -1));

        jLlbTitulo16.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLlbTitulo16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLlbTitulo16.setText("1.6");
        jLlbTitulo16.setToolTipText("");
        jLlbTitulo16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jLlbTitulo16, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 10, 40, -1));

        jLlbTitulo15.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLlbTitulo15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLlbTitulo15.setText("1.5");
        jLlbTitulo15.setToolTipText("");
        jLlbTitulo15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jLlbTitulo15, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 10, 40, -1));

        jLlbTitulo14.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLlbTitulo14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLlbTitulo14.setText("1.4");
        jLlbTitulo14.setToolTipText("");
        jLlbTitulo14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jLlbTitulo14, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 10, 40, -1));

        jLlbTitulo13.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLlbTitulo13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLlbTitulo13.setText("1.3");
        jLlbTitulo13.setToolTipText("");
        jLlbTitulo13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jLlbTitulo13, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 10, 40, -1));

        jLlbTitulo12.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLlbTitulo12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLlbTitulo12.setText("1.2");
        jLlbTitulo12.setToolTipText("");
        jLlbTitulo12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jLlbTitulo12, new org.netbeans.lib.awtextra.AbsoluteConstraints(686, 10, 40, -1));

        jSpdTop.setAlignmentX(0.0F);
        jSpdTop.setAlignmentY(0.0F);
        jPanelSuperiorVestibularCuadranteUno.add(jSpdTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 649, -1));

        jSpt1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSpt1.setAlignmentX(0.0F);
        jSpt1.setAlignmentY(0.0F);
        jPanelSuperiorVestibularCuadranteUno.add(jSpt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 61, 10, 310));

        jBtnImplante18.setText("No");
        jBtnImplante18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnImplante18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnImplante18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnImplante18ActionPerformed(evt);
            }
        });
        jPanelSuperiorVestibularCuadranteUno.add(jBtnImplante18, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 70, 73, 20));

        jSpt3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSpt3.setAlignmentX(0.0F);
        jSpt3.setAlignmentY(0.0F);
        jPanelSuperiorVestibularCuadranteUno.add(jSpt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 61, 10, 310));

        jSpt2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSpt2.setAlignmentX(0.0F);
        jSpt2.setAlignmentY(0.0F);
        jPanelSuperiorVestibularCuadranteUno.add(jSpt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 61, 10, 310));

        jLblFurcaSobreImagen18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblFurcaSobreImagen18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dental/imagenes/dientes/imagenes/FurcaVacio_18x18.png"))); // NOI18N
        jPanelSuperiorVestibularCuadranteUno.add(jLblFurcaSobreImagen18, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 405, -1, -1));

        jLblImagenVestibularDiente18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblImagenVestibularDiente18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dental/imagenes/dientes/dientes_superior/sin_tornillo/a/periodontograma-dientes-arriba-18.png"))); // NOI18N
        jLblImagenVestibularDiente18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jLblImagenVestibularDiente18, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 335, 56, 141));

        jTxtMargenGingivalMedia18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTxtMargenGingivalMedia18.setText("1");
        jTxtMargenGingivalMedia18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTxtMargenGingivalMedia18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTxtMargenGingivalMedia18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jTxtMargenGingivalMedia18, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 280, 23, 20));

        jTxtAnchuraEncia18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTxtAnchuraEncia18.setText("1");
        jTxtAnchuraEncia18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTxtAnchuraEncia18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTxtAnchuraEncia18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jTxtAnchuraEncia18, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 250, 73, 20));

        jTxtMargenGingivalMesial18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTxtMargenGingivalMesial18.setText("1");
        jTxtMargenGingivalMesial18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTxtMargenGingivalMesial18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTxtMargenGingivalMesial18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jTxtMargenGingivalMesial18, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 280, 23, 20));

        jTxtMargenGingivalDistal18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTxtMargenGingivalDistal18.setText("1");
        jTxtMargenGingivalDistal18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTxtMargenGingivalDistal18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTxtMargenGingivalDistal18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jTxtMargenGingivalDistal18, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 280, 23, 20));

        jTxtProfundidadMesial18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTxtProfundidadMesial18.setText("1");
        jTxtProfundidadMesial18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTxtProfundidadMesial18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTxtProfundidadMesial18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jTxtProfundidadMesial18, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 310, 23, 20));

        jTxtProfundidadMedia18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTxtProfundidadMedia18.setText("1");
        jTxtProfundidadMedia18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTxtProfundidadMedia18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTxtProfundidadMedia18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jTxtProfundidadMedia18, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 310, 23, 20));

        jTxtProfundidadDistal18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTxtProfundidadDistal18.setText("1");
        jTxtProfundidadDistal18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTxtProfundidadDistal18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTxtProfundidadDistal18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jTxtProfundidadDistal18, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 310, 23, 20));

        jTxtPlacaMesial18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTxtPlacaMesial18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTxtPlacaMesial18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTxtPlacaMesial18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jTxtPlacaMesial18, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 220, 23, 20));

        jTxtPlacaMedia18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTxtPlacaMedia18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTxtPlacaMedia18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTxtPlacaMedia18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jTxtPlacaMedia18, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 220, 23, 20));

        jTxtPlacaDistal18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTxtPlacaDistal18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTxtPlacaDistal18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTxtPlacaDistal18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jTxtPlacaDistal18, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 220, 23, 20));

        jTxtSangradoMesial18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTxtSangradoMesial18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTxtSangradoMesial18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTxtSangradoMesial18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jTxtSangradoMesial18, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 190, 23, 20));

        jTxtSangradoMedia18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTxtSangradoMedia18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTxtSangradoMedia18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTxtSangradoMedia18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jTxtSangradoMedia18, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 190, 23, 20));

        jTxtSangradoDistal18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTxtSangradoDistal18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTxtSangradoDistal18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTxtSangradoDistal18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jTxtSangradoDistal18, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 190, 23, 20));

        jTxtFurca18.setForeground(new java.awt.Color(255, 255, 255));
        jTxtFurca18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTxtFurca18.setAlignmentY(0.0F);
        jTxtFurca18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTxtFurca18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTxtFurca18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jTxtFurca18.setName(""); // NOI18N
        jPanelSuperiorVestibularCuadranteUno.add(jTxtFurca18, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 160, 73, 20));

        jTxtMovilidad18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTxtMovilidad18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTxtMovilidad18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTxtMovilidad18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jTxtMovilidad18, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 100, 73, 20));

        jTxtPronosticoIndividual18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTxtPronosticoIndividual18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTxtPronosticoIndividual18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTxtPronosticoIndividual18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jTxtPronosticoIndividual18, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 130, 73, 20));

        jBtnImplante17.setText("No");
        jBtnImplante17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnImplante17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jBtnImplante17, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 70, 73, 20));

        jTxtMovilidad17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTxtMovilidad17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTxtMovilidad17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTxtMovilidad17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jTxtMovilidad17, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 100, 73, 20));

        jTxtPronosticoIndividual17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTxtPronosticoIndividual17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTxtPronosticoIndividual17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTxtPronosticoIndividual17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jTxtPronosticoIndividual17, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 130, 73, 20));

        jTxtFurca17.setForeground(new java.awt.Color(255, 255, 255));
        jTxtFurca17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTxtFurca17.setAlignmentY(0.0F);
        jTxtFurca17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTxtFurca17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTxtFurca17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jTxtFurca17.setName(""); // NOI18N
        jPanelSuperiorVestibularCuadranteUno.add(jTxtFurca17, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 160, 73, 20));

        jTxtSangradoMesial17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTxtSangradoMesial17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTxtSangradoMesial17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTxtSangradoMesial17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jTxtSangradoMesial17, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 190, 23, 20));

        jTxtPlacaMesial17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTxtPlacaMesial17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTxtPlacaMesial17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTxtPlacaMesial17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jTxtPlacaMesial17, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 220, 23, 20));

        jTxtAnchuraEncia17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTxtAnchuraEncia17.setText("1");
        jTxtAnchuraEncia17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTxtAnchuraEncia17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTxtAnchuraEncia17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jTxtAnchuraEncia17, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 250, 73, 20));

        jTxtMargenGingivalMesial17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTxtMargenGingivalMesial17.setText("1");
        jTxtMargenGingivalMesial17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTxtMargenGingivalMesial17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTxtMargenGingivalMesial17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jTxtMargenGingivalMesial17, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 280, 23, 20));

        jTxtProfundidadMesial17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTxtProfundidadMesial17.setText("1");
        jTxtProfundidadMesial17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTxtProfundidadMesial17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTxtProfundidadMesial17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jTxtProfundidadMesial17, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 310, 23, 20));

        jLblFurcaSobreImagen17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblFurcaSobreImagen17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dental/imagenes/dientes/imagenes/FurcaVacio_18x18.png"))); // NOI18N
        jPanelSuperiorVestibularCuadranteUno.add(jLblFurcaSobreImagen17, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 405, -1, -1));

        jLblImagenVestibularDiente17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblImagenVestibularDiente17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dental/imagenes/dientes/dientes_superior/sin_tornillo/a/periodontograma-dientes-arriba-17.png"))); // NOI18N
        jLblImagenVestibularDiente17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jLblImagenVestibularDiente17, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 335, 56, 141));

        jTxtPlacaMedia17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTxtPlacaMedia17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTxtPlacaMedia17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTxtPlacaMedia17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jTxtPlacaMedia17, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 23, 20));

        jTxtSangradoMedia17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTxtSangradoMedia17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTxtSangradoMedia17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTxtSangradoMedia17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jTxtSangradoMedia17, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 23, 20));

        jTxtSangradoDistal17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTxtSangradoDistal17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTxtSangradoDistal17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTxtSangradoDistal17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jTxtSangradoDistal17, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 190, 23, 20));

        jTxtPlacaDistal17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTxtPlacaDistal17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTxtPlacaDistal17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTxtPlacaDistal17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jTxtPlacaDistal17, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 220, 23, 20));

        jTxtMargenGingivalMedia17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTxtMargenGingivalMedia17.setText("1");
        jTxtMargenGingivalMedia17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTxtMargenGingivalMedia17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTxtMargenGingivalMedia17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jTxtMargenGingivalMedia17, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 23, 20));

        jTxtProfundidadMedia17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTxtProfundidadMedia17.setText("1");
        jTxtProfundidadMedia17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTxtProfundidadMedia17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTxtProfundidadMedia17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jTxtProfundidadMedia17, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 23, 20));

        jTxtMargenGingivalDistal17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTxtMargenGingivalDistal17.setText("1");
        jTxtMargenGingivalDistal17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTxtMargenGingivalDistal17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTxtMargenGingivalDistal17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jTxtMargenGingivalDistal17, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 280, 23, 20));

        jTxtProfundidadDistal17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTxtProfundidadDistal17.setText("1");
        jTxtProfundidadDistal17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTxtProfundidadDistal17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTxtProfundidadDistal17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jTxtProfundidadDistal17, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 310, 23, 20));

        jSpt4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSpt4.setAlignmentX(0.0F);
        jSpt4.setAlignmentY(0.0F);
        jPanelSuperiorVestibularCuadranteUno.add(jSpt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 61, 10, 310));

        jSpt5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSpt5.setAlignmentX(0.0F);
        jSpt5.setAlignmentY(0.0F);
        jPanelSuperiorVestibularCuadranteUno.add(jSpt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 61, 10, 310));

        jSpt6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSpt6.setAlignmentX(0.0F);
        jSpt6.setAlignmentY(0.0F);
        jPanelSuperiorVestibularCuadranteUno.add(jSpt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 61, 10, 310));

        jSpt7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSpt7.setAlignmentX(0.0F);
        jSpt7.setAlignmentY(0.0F);
        jPanelSuperiorVestibularCuadranteUno.add(jSpt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(666, 61, 10, 310));

        jSpt8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSpt8.setAlignmentX(0.0F);
        jSpt8.setAlignmentY(0.0F);
        jPanelSuperiorVestibularCuadranteUno.add(jSpt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(747, 61, 10, 310));

        jSpt9.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSpt9.setAlignmentX(0.0F);
        jSpt9.setAlignmentY(0.0F);
        jPanelSuperiorVestibularCuadranteUno.add(jSpt9, new org.netbeans.lib.awtextra.AbsoluteConstraints(828, 61, 10, 310));

        jBtnImplante11.setText("No");
        jBtnImplante11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnImplante11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jBtnImplante11, new org.netbeans.lib.awtextra.AbsoluteConstraints(751, 70, 73, 20));

        jTxtMovilidad11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTxtMovilidad11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTxtMovilidad11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTxtMovilidad11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jTxtMovilidad11, new org.netbeans.lib.awtextra.AbsoluteConstraints(751, 100, 73, 20));

        jTxtPronosticoIndividual11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTxtPronosticoIndividual11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTxtPronosticoIndividual11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTxtPronosticoIndividual11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jTxtPronosticoIndividual11, new org.netbeans.lib.awtextra.AbsoluteConstraints(751, 130, 73, 20));

        jTxtFurca11.setForeground(new java.awt.Color(255, 255, 255));
        jTxtFurca11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTxtFurca11.setAlignmentY(0.0F);
        jTxtFurca11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTxtFurca11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTxtFurca11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jTxtFurca11.setName(""); // NOI18N
        jPanelSuperiorVestibularCuadranteUno.add(jTxtFurca11, new org.netbeans.lib.awtextra.AbsoluteConstraints(751, 160, 73, 20));

        jTxtSangradoMesial11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTxtSangradoMesial11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTxtSangradoMesial11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTxtSangradoMesial11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jTxtSangradoMesial11, new org.netbeans.lib.awtextra.AbsoluteConstraints(751, 190, 23, 20));

        jTxtPlacaMesial11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTxtPlacaMesial11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTxtPlacaMesial11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTxtPlacaMesial11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jTxtPlacaMesial11, new org.netbeans.lib.awtextra.AbsoluteConstraints(751, 220, 23, 20));

        jTxtAnchuraEncia11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTxtAnchuraEncia11.setText("1");
        jTxtAnchuraEncia11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTxtAnchuraEncia11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTxtAnchuraEncia11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jTxtAnchuraEncia11, new org.netbeans.lib.awtextra.AbsoluteConstraints(751, 250, 73, 20));

        jTxtMargenGingivalMesial11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTxtMargenGingivalMesial11.setText("1");
        jTxtMargenGingivalMesial11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTxtMargenGingivalMesial11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTxtMargenGingivalMesial11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jTxtMargenGingivalMesial11, new org.netbeans.lib.awtextra.AbsoluteConstraints(751, 280, 23, 20));

        jTxtProfundidadMesial11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTxtProfundidadMesial11.setText("1");
        jTxtProfundidadMesial11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTxtProfundidadMesial11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTxtProfundidadMesial11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jTxtProfundidadMesial11, new org.netbeans.lib.awtextra.AbsoluteConstraints(751, 310, 23, 20));

        jLblImagenVestibularDiente11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblImagenVestibularDiente11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dental/imagenes/dientes/dientes_superior/sin_tornillo/a/periodontograma-dientes-arriba-11.png"))); // NOI18N
        jLblImagenVestibularDiente11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jLblImagenVestibularDiente11, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 335, 56, 141));

        jLblImagenVestibularDiente12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblImagenVestibularDiente12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dental/imagenes/dientes/dientes_superior/sin_tornillo/a/periodontograma-dientes-arriba-12.png"))); // NOI18N
        jLblImagenVestibularDiente12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jLblImagenVestibularDiente12, new org.netbeans.lib.awtextra.AbsoluteConstraints(679, 335, 56, 141));

        jLblImagenVestibularDiente13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblImagenVestibularDiente13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dental/imagenes/dientes/dientes_superior/sin_tornillo/a/periodontograma-dientes-arriba-13.png"))); // NOI18N
        jLblImagenVestibularDiente13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jLblImagenVestibularDiente13, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 335, 56, 141));

        jLblImagenVestibularDiente14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblImagenVestibularDiente14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dental/imagenes/dientes/dientes_superior/sin_tornillo/a/periodontograma-dientes-arriba-14.png"))); // NOI18N
        jLblImagenVestibularDiente14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jLblImagenVestibularDiente14, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 335, 56, 141));

        jLblImagenVestibularDiente15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblImagenVestibularDiente15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dental/imagenes/dientes/dientes_superior/sin_tornillo/a/periodontograma-dientes-arriba-15.png"))); // NOI18N
        jLblImagenVestibularDiente15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jLblImagenVestibularDiente15, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 335, 56, 141));

        jLblImagenVestibularDiente16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblImagenVestibularDiente16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dental/imagenes/dientes/dientes_superior/sin_tornillo/a/periodontograma-dientes-arriba-16.png"))); // NOI18N
        jLblImagenVestibularDiente16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelSuperiorVestibularCuadranteUno.add(jLblImagenVestibularDiente16, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 335, 56, 141));

        getContentPane().add(jPanelSuperiorVestibularCuadranteUno);
        jPanelSuperiorVestibularCuadranteUno.setBounds(260, 10, 860, 580);

        jLblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dental/imagenes/FondoSecundario.jpg"))); // NOI18N
        getContentPane().add(jLblFondo);
        jLblFondo.setBounds(0, 0, 1300, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnImplante18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnImplante18ActionPerformed
        if (ConstantesURLDientes.NO_TIENE_IMPLANTE.equals(jBtnImplante18.getText().trim())) {
            jLblImagenVestibularDiente18.setIcon(new javax.swing.ImageIcon(getClass().getResource(ConstantesURLDientes.DIENTE_SUPERIOR_CON_TORNILLO_18)));
            jBtnImplante18.setText(ConstantesURLDientes.SI_TIENE_IMPLANTE);
        } else {
            jLblImagenVestibularDiente18.setIcon(new javax.swing.ImageIcon(getClass().getResource(ConstantesURLDientes.DIENTE_SUPERIOR_SIN_TORNILLO_18)));
            jBtnImplante18.setText(ConstantesURLDientes.NO_TIENE_IMPLANTE);
        }
    }//GEN-LAST:event_jBtnImplante18ActionPerformed

//    @Override
//    public void paint(Graphics graphics) {
//        super.paintComponents(graphics);
//        repaint();
//        graphics.setColor(Color.blue);
//        graphics.drawOval(194, 270, 20, 20);
//        //jPanelSuperiorVestibularCuadranteUno.add(graphics);
//        //graphics.fillOval(350, 270, 50, 70);
//        graphics.fillOval(194, 270, 20, 20);
//        
//        graphics.drawOval(220, 500, 20, 20);
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogPeriodontograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogPeriodontograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogPeriodontograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogPeriodontograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialogPeriodontograma dialog = new JDialogPeriodontograma(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnImplante11;
    private javax.swing.JButton jBtnImplante17;
    private javax.swing.JButton jBtnImplante18;
    private javax.swing.JLabel jLblFondo;
    private javax.swing.JLabel jLblFurcaSobreImagen17;
    private javax.swing.JLabel jLblFurcaSobreImagen18;
    private javax.swing.JLabel jLblImagenVestibularDiente11;
    private javax.swing.JLabel jLblImagenVestibularDiente12;
    private javax.swing.JLabel jLblImagenVestibularDiente13;
    private javax.swing.JLabel jLblImagenVestibularDiente14;
    private javax.swing.JLabel jLblImagenVestibularDiente15;
    private javax.swing.JLabel jLblImagenVestibularDiente16;
    private javax.swing.JLabel jLblImagenVestibularDiente17;
    private javax.swing.JLabel jLblImagenVestibularDiente18;
    private javax.swing.JLabel jLlbIAnchuraEncia;
    private javax.swing.JLabel jLlbIFurca;
    private javax.swing.JLabel jLlbIImplante1;
    private javax.swing.JLabel jLlbIMargenGingival;
    private javax.swing.JLabel jLlbIMovilidad;
    private javax.swing.JLabel jLlbIPlaca;
    private javax.swing.JLabel jLlbIProfundidadSondaje;
    private javax.swing.JLabel jLlbIPronostico;
    private javax.swing.JLabel jLlbISangradoSuturacion;
    private javax.swing.JLabel jLlbTitulo11;
    private javax.swing.JLabel jLlbTitulo12;
    private javax.swing.JLabel jLlbTitulo13;
    private javax.swing.JLabel jLlbTitulo14;
    private javax.swing.JLabel jLlbTitulo15;
    private javax.swing.JLabel jLlbTitulo16;
    private javax.swing.JLabel jLlbTitulo17;
    private javax.swing.JLabel jLlbTitulo18;
    private javax.swing.JPanel jPanelSuperiorVestibularCuadranteUno;
    private javax.swing.JSeparator jSpdTop;
    private javax.swing.JSeparator jSpt1;
    private javax.swing.JSeparator jSpt2;
    private javax.swing.JSeparator jSpt3;
    private javax.swing.JSeparator jSpt4;
    private javax.swing.JSeparator jSpt5;
    private javax.swing.JSeparator jSpt6;
    private javax.swing.JSeparator jSpt7;
    private javax.swing.JSeparator jSpt8;
    private javax.swing.JSeparator jSpt9;
    private javax.swing.JLabel jTxtAnchuraEncia11;
    private javax.swing.JLabel jTxtAnchuraEncia17;
    private javax.swing.JLabel jTxtAnchuraEncia18;
    private javax.swing.JLabel jTxtFurca11;
    private javax.swing.JLabel jTxtFurca17;
    private javax.swing.JLabel jTxtFurca18;
    private javax.swing.JLabel jTxtMargenGingivalDistal17;
    private javax.swing.JLabel jTxtMargenGingivalDistal18;
    private javax.swing.JLabel jTxtMargenGingivalMedia17;
    private javax.swing.JLabel jTxtMargenGingivalMedia18;
    private javax.swing.JLabel jTxtMargenGingivalMesial11;
    private javax.swing.JLabel jTxtMargenGingivalMesial17;
    private javax.swing.JLabel jTxtMargenGingivalMesial18;
    private javax.swing.JLabel jTxtMovilidad11;
    private javax.swing.JLabel jTxtMovilidad17;
    private javax.swing.JLabel jTxtMovilidad18;
    private javax.swing.JLabel jTxtPlacaDistal17;
    private javax.swing.JLabel jTxtPlacaDistal18;
    private javax.swing.JLabel jTxtPlacaMedia17;
    private javax.swing.JLabel jTxtPlacaMedia18;
    private javax.swing.JLabel jTxtPlacaMesial11;
    private javax.swing.JLabel jTxtPlacaMesial17;
    private javax.swing.JLabel jTxtPlacaMesial18;
    private javax.swing.JLabel jTxtProfundidadDistal17;
    private javax.swing.JLabel jTxtProfundidadDistal18;
    private javax.swing.JLabel jTxtProfundidadMedia17;
    private javax.swing.JLabel jTxtProfundidadMedia18;
    private javax.swing.JLabel jTxtProfundidadMesial11;
    private javax.swing.JLabel jTxtProfundidadMesial17;
    private javax.swing.JLabel jTxtProfundidadMesial18;
    private javax.swing.JLabel jTxtPronosticoIndividual11;
    private javax.swing.JLabel jTxtPronosticoIndividual17;
    private javax.swing.JLabel jTxtPronosticoIndividual18;
    private javax.swing.JLabel jTxtSangradoDistal17;
    private javax.swing.JLabel jTxtSangradoDistal18;
    private javax.swing.JLabel jTxtSangradoMedia17;
    private javax.swing.JLabel jTxtSangradoMedia18;
    private javax.swing.JLabel jTxtSangradoMesial11;
    private javax.swing.JLabel jTxtSangradoMesial17;
    private javax.swing.JLabel jTxtSangradoMesial18;
    // End of variables declaration//GEN-END:variables
}
