/**
 * JFrmMenuPrincipal.java
 * 09/12/2015
 */
package org.dental.pantallas;

import java.awt.Dimension;
import javax.swing.ImageIcon;
import org.dental.constantes.Constantes;
import org.dental.constantes.ConstantesTipoLetra;
import org.dental.constantes.ConstantesURLS;

/**
 *
 * @author Henry Salinas A.
 * @version: 1.0
 */
public class JFrmMenuPrincipal extends javax.swing.JFrame {

    /**
     * Para la posici&oacute;n de los jPanelGroup
     */
    private final Integer POSICION_X = 100;
    private final Integer POSICION_Y = 300;

    /**
     * Para el tamanio de la letra de cada uno de los botones internos que tenga
     * un Panel
     */
    private final Integer TAMANIO_LETRA_12 = 12;
    private final Integer TAMANIO_LETRA_15 = 15;

    /**
     * Creates new form JFrmMenuPrincipal
     */
    public JFrmMenuPrincipal() {
        initComponents();
        initJpanelGroups();
        Dimension screenSize = Constantes.dimensionScreen(getGraphicsConfiguration());
        this.setSize(screenSize.width, screenSize.height);
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource(ConstantesURLS.RUTA_IMAGEN_FONDO_MENU_PRINCIPAL)).getImage());
    }

    private void initJpanelGroups() {
        jPanelGrupoUsuarios.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Grupo Usuarios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font(ConstantesTipoLetra.COPPERPLATE_TYPE, ConstantesTipoLetra.COPPERPLATE_STYLE, 16), new java.awt.Color(0, 153, 153)));
        jPanelGrupoUsuarios.setVisible(false);

        jPanelPacientes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pacientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font(ConstantesTipoLetra.COPPERPLATE_TYPE, ConstantesTipoLetra.COPPERPLATE_STYLE, 16), new java.awt.Color(0, 153, 153)));
        jPanelPacientes.setVisible(false);

//        jPanelProductos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font(ConstantesTipoLetra.CENTURY_GOTHIC_TYPE, ConstantesTipoLetra.CENTURY_GOTHIC_STYLE, ConstantesTipoLetra.CENTURY_GOTHIC_SIZE)));
//        jPanelProductos.setVisible(false);
//
//        jPanelMantenimiento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mantenimiento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font(ConstantesTipoLetra.CENTURY_GOTHIC_TYPE, ConstantesTipoLetra.CENTURY_GOTHIC_STYLE, ConstantesTipoLetra.CENTURY_GOTHIC_SIZE)));
//        jPanelMantenimiento.setVisible(false);
//
//        jPanelFacturacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Facturación", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font(ConstantesTipoLetra.CENTURY_GOTHIC_TYPE, ConstantesTipoLetra.CENTURY_GOTHIC_STYLE, ConstantesTipoLetra.CENTURY_GOTHIC_SIZE)));
//        jPanelFacturacion.setVisible(false);
//
//        jPanelReportes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reportes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font(ConstantesTipoLetra.CENTURY_GOTHIC_TYPE, ConstantesTipoLetra.CENTURY_GOTHIC_STYLE, ConstantesTipoLetra.CENTURY_GOTHIC_SIZE)));
//        jPanelReportes.setVisible(false);
//
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBntUsuarios = new javax.swing.JLabel();
        jPanelGrupoUsuarios = new javax.swing.JLayeredPane();
        jlblEmpleados5 = new javax.swing.JLabel();
        jlblUsuarios5 = new javax.swing.JLabel();
        jBntPacientes = new javax.swing.JLabel();
        jPanelPacientes = new javax.swing.JLayeredPane();
        jBntNuevoPaciente = new javax.swing.JLabel();
        jBntBuscarPaciente = new javax.swing.JLabel();
        jBntModificarPaciente = new javax.swing.JLabel();
        jLblImagenFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1240, 720));
        setResizable(false);
        getContentPane().setLayout(null);

        jBntUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBntUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dental/imagenes/grupoUsuarios_64x64.png"))); // NOI18N
        jBntUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBntUsuarios.setMaximumSize(new java.awt.Dimension(128, 128));
        jBntUsuarios.setMinimumSize(new java.awt.Dimension(128, 128));
        jBntUsuarios.setPreferredSize(new java.awt.Dimension(128, 128));
        jBntUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBntUsuariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBntUsuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBntUsuariosMouseExited(evt);
            }
        });
        getContentPane().add(jBntUsuarios);
        jBntUsuarios.setBounds(330, 70, 72, 72);

        jPanelGrupoUsuarios.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Grupo Usuarios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Copperplate Gothic Light", 0, 14), new java.awt.Color(0, 153, 153))); // NOI18N

        jlblEmpleados5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jlblEmpleados5.setText("Agregar");
        jlblEmpleados5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelGrupoUsuarios.add(jlblEmpleados5);
        jlblEmpleados5.setBounds(30, 40, 120, 16);

        jlblUsuarios5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jlblUsuarios5.setText("Consultar");
        jlblUsuarios5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelGrupoUsuarios.add(jlblUsuarios5);
        jlblUsuarios5.setBounds(30, 70, 120, 16);

        getContentPane().add(jPanelGrupoUsuarios);
        jPanelGrupoUsuarios.setBounds(60, 520, 340, 170);

        jBntPacientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBntPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dental/imagenes/Pacientes_48x48.png"))); // NOI18N
        jBntPacientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBntPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBntPacientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBntPacientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBntPacientesMouseExited(evt);
            }
        });
        getContentPane().add(jBntPacientes);
        jBntPacientes.setBounds(480, 130, 64, 64);

        jPanelPacientes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pacientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Copperplate Gothic Light", 0, 14), new java.awt.Color(0, 153, 153))); // NOI18N

        jBntNuevoPaciente.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jBntNuevoPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dental/imagenes/PacienteNuevo_24x24.png"))); // NOI18N
        jBntNuevoPaciente.setText("Nuevo");
        jBntNuevoPaciente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBntNuevoPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBntNuevoPacienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBntNuevoPacienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBntNuevoPacienteMouseExited(evt);
            }
        });
        jPanelPacientes.add(jBntNuevoPaciente);
        jBntNuevoPaciente.setBounds(30, 30, 120, 30);

        jBntBuscarPaciente.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jBntBuscarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dental/imagenes/PacienteBuscar_24x24.png"))); // NOI18N
        jBntBuscarPaciente.setText("Buscar");
        jBntBuscarPaciente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBntBuscarPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBntBuscarPacienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBntBuscarPacienteMouseExited(evt);
            }
        });
        jPanelPacientes.add(jBntBuscarPaciente);
        jBntBuscarPaciente.setBounds(30, 90, 120, 30);

        jBntModificarPaciente.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jBntModificarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dental/imagenes/PacienteNuevo_24x24.png"))); // NOI18N
        jBntModificarPaciente.setText("Modificar");
        jBntModificarPaciente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBntModificarPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBntModificarPacienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBntModificarPacienteMouseExited(evt);
            }
        });
        jPanelPacientes.add(jBntModificarPaciente);
        jBntModificarPaciente.setBounds(30, 60, 120, 30);

        getContentPane().add(jPanelPacientes);
        jPanelPacientes.setBounds(410, 520, 340, 170);

        jLblImagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/dental/imagenes/FondoPrincipal.png"))); // NOI18N
        jLblImagenFondo.setPreferredSize(null);
        getContentPane().add(jLblImagenFondo);
        jLblImagenFondo.setBounds(0, 0, 1920, 880);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBntUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBntUsuariosMouseClicked
        jPanelGrupoUsuarios.setLocation(POSICION_X, POSICION_Y);
        jPanelGrupoUsuarios.setVisible(true);

        jPanelPacientes.setVisible(false);
//        jPanelGrupoUsuario.setLocation(POSICION_X, POSICION_Y);
//        jPanelGrupoUsuario.setVisible(true);
//
//        jPanelFacturacion.setVisible(false);
//        jPanelMantenimiento.setVisible(false);
//        jPanelProductos.setVisible(false);
//        jPanelReportes.setVisible(false);
//        jPanelClientes.setVisible(false);
    }//GEN-LAST:event_jBntUsuariosMouseClicked

    private void jBntUsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBntUsuariosMouseEntered
        jBntUsuarios.setFont(new java.awt.Font(ConstantesTipoLetra.COPPERPLATE_TYPE, ConstantesTipoLetra.COPPERPLATE_STYLE, ConstantesTipoLetra.TAMANIO_LETRA_MENU));
        jBntUsuarios.setForeground(new java.awt.Color(ConstantesTipoLetra.ColorLetraToolTipTextMenu.RED.toInt(), ConstantesTipoLetra.ColorLetraToolTipTextMenu.GREEN.toInt(), ConstantesTipoLetra.ColorLetraToolTipTextMenu.BLUE.toInt()));
        jBntUsuarios.setText("Usuarios");
        jBntUsuarios.setBounds(290, 40, 250, 128);
        jBntUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource(ConstantesURLS.RUTA_ICON_GRUPO_USUARIOS_96X96)));
    }//GEN-LAST:event_jBntUsuariosMouseEntered

    private void jBntUsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBntUsuariosMouseExited
        jBntUsuarios.setText("");
        jBntUsuarios.setBounds(330, 70, 72, 72);
        jBntUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource(ConstantesURLS.RUTA_ICON_GRUPO_USUARIOS_64X64)));
    }//GEN-LAST:event_jBntUsuariosMouseExited

    private void jBntPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBntPacientesMouseClicked
        jPanelPacientes.setLocation(POSICION_X, POSICION_Y);
        jPanelPacientes.setVisible(true);

        jPanelGrupoUsuarios.setVisible(false);
    }//GEN-LAST:event_jBntPacientesMouseClicked

    private void jBntPacientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBntPacientesMouseEntered
        jBntPacientes.setFont(new java.awt.Font(ConstantesTipoLetra.COPPERPLATE_TYPE, ConstantesTipoLetra.COPPERPLATE_STYLE, ConstantesTipoLetra.TAMANIO_LETRA_MENU));
        jBntPacientes.setForeground(new java.awt.Color(ConstantesTipoLetra.ColorLetraToolTipTextMenu.RED.toInt(), ConstantesTipoLetra.ColorLetraToolTipTextMenu.GREEN.toInt(), ConstantesTipoLetra.ColorLetraToolTipTextMenu.BLUE.toInt()));
        jBntPacientes.setText("Pacientes");
        jBntPacientes.setBounds(440, 100, 270, 128);
        jBntPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource(ConstantesURLS.RUTA_ICON_PACIENTES_64X64)));
    }//GEN-LAST:event_jBntPacientesMouseEntered

    private void jBntPacientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBntPacientesMouseExited
        jBntPacientes.setText("");
        jBntPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource(ConstantesURLS.RUTA_ICON_PACIENTES_48X48)));
        jBntPacientes.setBounds(480, 130, 64, 64);
    }//GEN-LAST:event_jBntPacientesMouseExited

    private void jBntNuevoPacienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBntNuevoPacienteMouseEntered
        jBntNuevoPaciente.setFont(new java.awt.Font("Century Gothic", 0, TAMANIO_LETRA_15));
    }//GEN-LAST:event_jBntNuevoPacienteMouseEntered

    private void jBntNuevoPacienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBntNuevoPacienteMouseExited
        jBntNuevoPaciente.setFont(new java.awt.Font("Century Gothic", 0, TAMANIO_LETRA_12));
    }//GEN-LAST:event_jBntNuevoPacienteMouseExited

    private void jBntModificarPacienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBntModificarPacienteMouseEntered
        jBntModificarPaciente.setFont(new java.awt.Font("Century Gothic", 0, TAMANIO_LETRA_15));
    }//GEN-LAST:event_jBntModificarPacienteMouseEntered

    private void jBntModificarPacienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBntModificarPacienteMouseExited
        jBntModificarPaciente.setFont(new java.awt.Font("Century Gothic", 0, TAMANIO_LETRA_12));
    }//GEN-LAST:event_jBntModificarPacienteMouseExited

    private void jBntBuscarPacienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBntBuscarPacienteMouseEntered
        jBntBuscarPaciente.setFont(new java.awt.Font("Century Gothic", 0, TAMANIO_LETRA_15));
    }//GEN-LAST:event_jBntBuscarPacienteMouseEntered

    private void jBntBuscarPacienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBntBuscarPacienteMouseExited
        jBntBuscarPaciente.setFont(new java.awt.Font("Century Gothic", 0, TAMANIO_LETRA_12));
    }//GEN-LAST:event_jBntBuscarPacienteMouseExited

    private void jBntNuevoPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBntNuevoPacienteMouseClicked
        jBntNuevoPaciente.setFont(new java.awt.Font("Century Gothic", 0, TAMANIO_LETRA_12));
        JDialogPaciente jDialogPaciente = new JDialogPaciente(this, true);
        //jDialogPaciente.setUsuario(usuario);
        jDialogPaciente.setLocationRelativeTo(this);
        jDialogPaciente.setVisible(true);

    }//GEN-LAST:event_jBntNuevoPacienteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jBntBuscarPaciente;
    private javax.swing.JLabel jBntModificarPaciente;
    private javax.swing.JLabel jBntNuevoPaciente;
    private javax.swing.JLabel jBntPacientes;
    private javax.swing.JLabel jBntUsuarios;
    private javax.swing.JLabel jLblImagenFondo;
    private javax.swing.JLayeredPane jPanelGrupoUsuarios;
    private javax.swing.JLayeredPane jPanelPacientes;
    private javax.swing.JLabel jlblEmpleados5;
    private javax.swing.JLabel jlblUsuarios5;
    // End of variables declaration//GEN-END:variables
}
